version: '3.9'

services:

  todo-app:
    image: todo-app
    container_name: todo-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://todo-db:5432/todoappdb
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres

    depends_on:
      - todo-db
  todo-db:
    container_name: todo-db
    image: postgres:12
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoappdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}